services:
  app:
    image: luka762/infinite-canvas:latest
    container_name: infinite-canvas
    env_file:
      - .env
    environment:
      API_BASE_URL: http://127.0.0.1:9080
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
